### ISSUE TITLE
Broken line for the first muli-line item of a bulleted (unordered) list

### ISSUE THREAD

**Issue by Nabav** [borgar/textile-js#88]
Originally reported here: https://github.com/GehDoc/vscode-textile-preview/issues/75, but I think, I should have reported here.

**Describe the bug**
As illustrated below, just for the first item of a bulleted list that is written in multiple lines, the preview is also rendering multiple lines. It is not the case for the next multi-line items.

![image](https://github.com/borgar/textile-js/assets/24389873/1041eb75-d4ea-4e18-8815-f7ea50131489)

**To Reproduce**
Use this to reproduce the behavior:

```textile
* Item number 1 in
  two lines
* Item number 2 in
  two lines
* Item number 3 in
  two lines

* Item number 1 in single line
* Item number 2 in
  two lines
* Item number 3 in
  two lines
```

**Expected behavior**
As rendered in https://textile-lang.com

![image](https://github.com/borgar/textile-js/assets/24389873/637f2a04-8871-4f6d-9a6d-3ac9df98184e)

**Comment by borgar** [comment]
Looks like Textile PHP has become consistent with the rule "don't line-break when next rule starts with a space" at some point recently. I have a test in here (which comes from RedCloth) that says this should not be the behaviour:

https://github.com/borgar/textile-js/blob/35b66e975651ee01738ff36134f496dcfadf4f6f/test/lists.js#L15-L28

It looks like the PHP version is consistent in this behaviour now and I think this is a good rule that makes sense. So I consider this a bug in textile-js. It's an easy fix, but will have to be shipped with the now <i>aa</i>aalmost ready 3.0.

**Comment by Nabav** [comment]
Fixed in https://github.com/GehDoc/textile-js/issues/5

**Comment by borgar** [comment]
The error still exists in this library, so I would like the ticket open until a fix is shipped. 🙂
